# -*- coding: utf-8 -*-
"""Apply Vietnamese diacritic phrase replacements to summary, then rebuild study JS."""
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parent


def load_pairs() -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    p = ROOT / "vi_phrases.tsv"
    if p.exists():
        for line in p.read_text(encoding="utf-8").splitlines():
            # stop if python junk starts
            if line.startswith("from pathlib") or line.startswith("text ="):
                break
            if "\t" not in line:
                continue
            a, b = line.split("\t", 1)
            a, b = a.strip(), b.strip()
            if a and b and a != b:
                pairs.append((a, b))
    # Always ensure high-priority header pairs
    extra = [
        ("TOM TAT CHI TIET ON THI", "TÓM TẮT CHI TIẾT ÔN THI"),
        ("BAN NAY CO NOI DUNG GIAI THICH DAY DU (khong chi tieu de).",
         "BẢN NÀY CÓ NỘI DUNG GIẢI THÍCH ĐẦY ĐỦ (không chỉ tiêu đề)."),
        ("Moi muc: dinh nghia + giai thich + vi du/cong thuc + diem hay ra de.",
         "Mỗi mục: định nghĩa + giải thích + ví dụ/công thức + điểm hay ra đề."),
        ("Ngon ngu: tieng Viet + giu thuan ngu tieng Anh nhu trong sach goc.",
         "Ngôn ngữ: tiếng Việt + giữ thuật ngữ tiếng Anh như trong sách gốc."),
        ("PHU LUC BO SUNG - CAC DIEM CAN DE TRA LOI CAU HOI MAU (test.txt)",
         "PHỤ LỤC BỔ SUNG — CÁC ĐIỂM CẦN ĐỂ TRẢ LỜI CÂU HỎI MẪU (test.txt)"),
        ("(Bo sung sau khi doi chieu de mau; DOC THEM PHAN NAY KHI ON DE)",
         "(Bổ sung sau khi đối chiếu đề mẫu; ĐỌC THÊM PHẦN NÀY KHI ÔN ĐỀ)"),
        ("HET PHU LUC BO SUNG", "HẾT PHỤ LỤC BỔ SUNG"),
        ("PHU LUC - CHECKLIST ON NHANH TRUOC THI", "PHỤ LỤC — CHECKLIST ÔN NHANH TRƯỚC THI"),
        ("Cach dung: doc tung muc -> tu viet lai so do -> lam bai Exercises cuoi chuong trong sach.",
         "Cách dùng: đọc từng mục → tự viết lại sơ đồ → làm bài Exercises cuối chương trong sách."),
        ("File nay thay the ban 'chi tieu de'; moi dong la noi dung on that.",
         "File này thay thế bản 'chỉ tiêu đề'; mỗi dòng là nội dung ôn thật."),
        ("Nguon: New FE Textbook Vol.1 & Vol.2 (vol1.docx, vol2.docx).",
         "Nguồn: New FE Textbook Vol.1 & Vol.2 (vol1.docx, vol2.docx)."),
        ("Ky thi FE", "Kỳ thi FE"),
        ("DIEM THI:", "ĐIỂM THI:"),
        ("VI DU", "VÍ DỤ"),
        ("Luu y:", "Lưu ý:"),
        ("Chuong nay", "Chương này"),
        ("giai thich", "giải thích"),
        ("may tinh", "máy tính"),
        ("du lieu", "dữ liệu"),
        ("bieu dien", "biểu diễn"),
        ("bo nho", "bộ nhớ"),
        ("hoat dong", "hoạt động"),
        ("nen tang", "nền tảng"),
        ("de hieu", "để hiểu"),
        ("cac chuong", "các chương"),
        ("Cau hinh", "Cấu hình"),
        ("co ban", "cơ bản"),
        ("Lich su", "Lịch sử"),
        ("Nam don vi chinh", "Năm đơn vị chính"),
        ("don vi chinh", "đơn vị chính"),
        ("khong chi tieu de", "không chỉ tiêu đề"),
        ("dinh nghia", "định nghĩa"),
        ("giai thich", "giải thích"),
        ("vi du", "ví dụ"),
        ("cong thuc", "công thức"),
        ("diem hay ra de", "điểm hay ra đề"),
        ("tieng Viet", "tiếng Việt"),
        ("thuan ngu", "thuật ngữ"),
        ("tieng Anh", "tiếng Anh"),
        ("sach goc", "sách gốc"),
        ("trang thai tien trinh", "trạng thái tiến trình"),
        ("dang chiem CPU", "đang chiếm CPU"),
        ("san sang chay", "sẵn sàng chạy"),
        ("dang cho", "đang chờ"),
        ("cho su kien", "chờ sự kiện"),
        ("ket thuc", "kết thúc"),
        ("bi treo", "bị treo"),
        ("tai nguyen", "tài nguyên"),
        ("khong chia se", "không chia sẻ"),
        ("dong thoi", "đồng thời"),
        ("chuoi vong doi", "chuỗi vòng đợi"),
        ("Phong ngua", "Phòng ngừa"),
        ("lang phi", "lãng phí"),
        ("cong bang", "công bằng"),
        ("doi mai", "đợi mãi"),
        ("tinh so", "tính số"),
        ("noi tiep", "nối tiếp"),
        ("song song", "song song"),
        ("dich TOAN BO", "dịch TOÀN BỘ"),
        ("truoc khi chay", "trước khi chạy"),
        ("KET HOP", "KẾT HỢP"),
        ("nap chuong trinh", "nạp chương trình"),
        ("vao bo nho", "vào bộ nhớ"),
        ("phan mem thap", "phần mềm thấp"),
        ("mat dien", "mất điện"),
        ("ngoai vi", "ngoại vi"),
        ("Muc dich", "Mục đích"),
        ("cai thien", "cải thiện"),
        ("tuong tac nguoi-may", "tương tác người-máy"),
        ("de dung", "dễ dùng"),
        ("de tiep can", "dễ tiếp cận"),
        ("giam loi nguoi dung", "giảm lỗi người dùng"),
        ("tang nang suat", "tăng năng suất"),
        ("giam dao tao", "giảm đào tạo"),
        ("KHONG phai muc tieu chinh", "KHÔNG phải mục tiêu chính"),
        ("luu theo thu tu", "lưu theo thứ tự"),
        ("doc lan luot", "đọc lần lượt"),
        ("truy cap nhanh", "truy cập nhanh"),
        ("trieu ban ghi", "triệu bản ghi"),
        ("khong sort", "không sort"),
        ("insert nhanh, search cham", "insert nhanh, search chậm"),
        ("xoa CA dinh nghia bang VA du lieu", "xóa CẢ định nghĩa bảng VÀ dữ liệu"),
        ("xoa dong", "xóa dòng"),
        ("xoa het dong", "xóa hết dòng"),
        ("giu cau truc", "giữ cấu trúc"),
        ("Tim luong cao thu 2 theo phong", "Tìm lương cao thứ 2 theo phòng"),
        ("Cong thuc", "Công thức"),
        ("Luu y don vi", "Lưu ý đơn vị"),
        ("trong de mang", "trong đề mạng"),
        ("So am", "Số âm"),
        ("bit cao nhat", "bit cao nhất"),
        ("la so am", "là số âm"),
        ("dao bit roi +1", "đảo bit rồi +1"),
        ("tri tuyet doi", "trị tuyệt đối"),
        ("them dau tru", "thêm dấu trừ"),
        ("thap phan", "thập phân"),
        ("bat phan", "bát phân"),
        ("chu so", "chữ số"),
        ("Trung to", "Trung tố"),
        ("Tien to", "Tiền tố"),
        ("Hau to", "Hậu tố"),
        ("uu tien hon", "ưu tiên hơn"),
        ("toan hang truoc", "toán hạng trước"),
        ("toan tu sau", "toán tử sau"),
        ("De thi hay cho bieu thuc", "Đề thi hay cho biểu thức"),
        ("chon dung chuoi postfix", "chọn đúng chuỗi postfix"),
        ("them dinh", "thêm đỉnh"),
        ("lay dinh", "lấy đỉnh"),
        ("dinh con lai", "đỉnh còn lại"),
        ("dau hang", "đầu hàng"),
        ("duyet tu dau", "duyệt từ đầu"),
        ("Chen X giua", "Chèn X giữa"),
        ("nut trai", "nút trái"),
        ("nut hien tai", "nút hiện tại"),
        ("nut phai", "nút phải"),
        ("TANG DAN", "TĂNG DẦN"),
        ("Cay nhi phan day du", "Cây nhị phân đầy đủ"),
        ("chieu cao toi thieu", "chiều cao tối thiểu"),
        ("can doc de", "cần đọc đề"),
        ("moi luot", "mỗi lượt"),
        ("phan tu lon ve cuoi", "phần tử lớn về cuối"),
        ("phan con lai", "phần còn lại"),
        ("doi len dau", "đổi lên đầu"),
        ("chua sort", "chưa sort"),
        ("chia de tri", "chia để trị"),
        ("khong can mang da sort", "không cần mảng đã sort"),
        ("dung ngay dau", "đúng ngay đầu"),
        ("CAN mang da sort", "CẦN mảng đã sort"),
        ("so lan so sanh toi da", "số lần so sánh tối đa"),
        ("toi da 3 lan", "tối đa 3 lần"),
        ("Chia bai toan thanh bai con giong nhau", "Chia bài toán thành bài con giống nhau"),
        ("giai roi ket hop", "giải rồi kết hợp"),
        ("thiet lap muc tieu", "thiết lập mục tiêu"),
        ("chinh sach", "chính sách"),
        ("danh gia rui ro", "đánh giá rủi ro"),
        ("tai san thong tin", "tài sản thông tin"),
        ("chon bien phap", "chọn biện pháp"),
        ("trien khai", "triển khai"),
        ("van hanh", "vận hành"),
        ("giam sat", "giám sát"),
        ("tinh trang", "tình trạng"),
        ("cai tien", "cải tiến"),
        ("Khong the xu ly het moi rui ro", "Không thể xử lý hết mọi rủi ro"),
        ("uoc luong thiet hai", "ước lượng thiệt hại"),
        ("tan suat", "tần suất"),
        ("xep hang uu tien", "xếp hạng ưu tiên"),
        ("muc do rui ro", "mức độ rủi ro"),
        ("Chinh sach the hien tu duy", "Chính sách thể hiện tư duy"),
        ("huong di cua to chuc", "hướng đi của tổ chức"),
        ("hanh vi va tieu chi phan doan", "hành vi và tiêu chí phán đoán"),
        ("dat muc an ninh", "đạt mức an ninh"),
        ("Ap dung toan to chuc", "Áp dụng toàn tổ chức"),
        ("khong phu thuoc tung san pham bao mat", "không phụ thuộc từng sản phẩm bảo mật"),
        ("cong bo vulnerability ra ben ngoai", "công bố vulnerability ra bên ngoài"),
        ("khong lo hong cho ben thu 3", "không lộ hổng cho bên thứ 3"),
        ("chinh xac va day du", "chính xác và đầy đủ"),
        ("dung luc can", "đúng lúc cần"),
        ("duoc uy quyen", "được ủy quyền"),
        ("1 khoa chung", "1 khóa chung"),
        ("kho chia khoa an toan", "khó chia khóa an toàn"),
        ("nhieu nguoi", "nhiều người"),
        ("CHAM hon", "CHẬM hơn"),
        ("cong khai", "công khai"),
        ("KHONG can phan phoi bi mat", "KHÔNG cần phân phối bí mật"),
        ("Hybrid thuc dung", "Hybrid thực dụng"),
        ("ngan lo hong NOI DUNG", "ngăn lộ hổng NỘI DUNG"),
        ("Dam bao noi dung khong bi sua trai phep", "Đảm bảo nội dung không bị sửa trái phép"),
        ("xac thuc nguoi ky", "xác thực người ký"),
        ("chu yeu", "chủ yếu"),
        ("han che user", "hạn chế user"),
        ("chung minh ban quyen", "chứng minh bản quyền"),
        ("cam ket bao tri", "cam kết bảo trì"),
        ("van tay", "vân tay"),
        ("long ban tay", "lòng bàn tay"),
        ("khuon mat", "khuôn mặt"),
        ("ma hoa / bao mat", "mã hóa / bảo mật"),
        ("chan tan cong loi ung dung web", "chặn tấn công lỗi ứng dụng web"),
        ("tich hop nhieu chuc nang bao mat", "tích hợp nhiều chức năng bảo mật"),
        ("thay client gui request", "thay client gửi request"),
        ("phia client", "phía client"),
        ("thay server nhan request", "thay server nhận request"),
        ("phia server", "phía server"),
        ("can bang tai", "cân bằng tải"),
        ("bao ve origin", "bảo vệ origin"),
        ("phat hien xam nhap", "phát hiện xâm nhập"),
        ("loc/chan may tram noi bo", "lọc/chặn máy trạm nội bộ"),
        ("thang ra mail server ngoai", "thẳng ra mail server ngoài"),
        ("giam spam may nhiem", "giảm spam máy nhiễm"),
        ("xac thuc domain", "xác thực domain"),
        ("doi tac canh bao som an ninh thong tin", "đối tác cảnh báo sớm an ninh thông tin"),
        ("o Nhat", "ở Nhật"),
        ("thuan tuy", "thuần túy"),
        ("so khop mau virus da biet", "so khớp mẫu virus đã biết"),
        ("hieu qua virus BIET", "hiệu quả virus BIẾT"),
        ("co ten virus", "có tên virus"),
        ("bat hanh vi la", "bắt hành vi lạ"),
        ("ten chinh xac", "tên chính xác"),
        ("qua don gian", "quá đơn giản"),
        ("khong dam bao restore", "không đảm bảo restore"),
        ("go virus", "gỡ virus"),
        ("xac minh danh tinh", "xác minh danh tính"),
        ("quen mat khau", "quên mật khẩu"),
        ("dat mat khau moi", "đặt mật khẩu mới"),
        ("giai ma hash", "giải mã hash"),
        ("hash 1 chieu", "hash 1 chiều"),
        ("gui password cu la nguy hiem", "gửi password cũ là nguy hiểm"),
        ("Loi dung con nguoi", "Lợi dụng con người"),
        ("khong can exploit ky thuat", "không cần exploit kỹ thuật"),
        ("gia danh nguoi uy quyen", "giả danh người ủy quyền"),
        ("goi dien hoi password", "gọi điện hỏi password"),
        ("tan cong lo hong OS", "tấn công lỗ hổng OS"),
        ("bang chuong trinh", "bằng chương trình"),
        ("Giao thuc ket hop xac thuc", "Giao thức kết hợp xác thực"),
        ("ma hoa du lieu truyen", "mã hóa dữ liệu truyền"),
        ("bao ve password mot phan", "bảo vệ password một phần"),
        ("uy quyen API", "ủy quyền API"),
        ("khung xac thuc mang", "khung xác thực mạng"),
        ("lap/thao goi du lieu truyen", "lắp/tháo gói dữ liệu truyền"),
        ("dieu khien loi truyen", "điều khiển lỗi truyền"),
        ("dinh dang phu hop duong truyen", "định dạng phù hợp đường truyền"),
        ("quay so", "quay số"),
        ("Tach biet chuc nang", "Tách biệt chức năng"),
        ("ngan gon", "ngắn gọn"),
        ("chia khe thoi gian", "chia khe thời gian"),
        ("tung kenh/user", "từng kênh/user"),
        ("chia bang tan so", "chia băng tần số"),
        ("chia buoc song anh sang", "chia bước sóng ánh sáng"),
        ("gan ma cho user", "gán mã cho user"),
        ("hinh anh chuyen dong", "hình ảnh chuyển động"),
        ("am thanh", "âm thanh"),
        ("du lieu nhi phan chung", "dữ liệu nhị phân chung"),
        ("truy cap nhanh hon", "truy cập nhanh hơn"),
        ("it chuyen dong co", "ít chuyển động cơ"),
        ("dung luong lon", "dung lượng lớn"),
        ("cham hon", "chậm hơn"),
        ("thoi gian tu gui yeu cau den nhan phan hoi", "thời gian từ gửi yêu cầu đến nhận phản hồi"),
        ("xac suat he thong dung duoc khi can", "xác suất hệ thống dùng được khi cần"),
        ("Payroll thang 1 lan", "Payroll tháng 1 lần"),
        ("Dat ve may bay can ngay", "Đặt vé máy bay cần ngay"),
        ("moi xu ly dồn 1 may trung tam", "mọi xử lý dồn 1 máy trung tâm"),
        ("nhieu may", "nhiều máy"),
        ("Quan ly file dong thoi nhieu user", "Quản lý file đồng thời nhiều user"),
        ("khoa/quyen truy cap, toan ven", "khóa/quyền truy cập, toàn vẹn"),
        ("Chiu trach nhiem scheduling", "Chịu trách nhiệm scheduling"),
        ("process nao nhan CPU", "process nào nhận CPU"),
        ("tom tat de", "tóm tắt đề"),
        ("don vi nho nhat", "đơn vị nhỏ nhất"),
        ("da ngon ngu quoc te", "đa ngôn ngữ quốc tế"),
        ("Tu khoa / cong thuc bo sung chot", "Từ khóa / công thức bổ sung chốt"),
        ("dam bao atomic transaction phan tan", "đảm bảo atomic transaction phân tán"),
        ("du an la temporary", "dự án là temporary"),
        ("co thoi han bat dau-ket thuc ro", "có thời hạn bắt đầu–kết thúc rõ"),
        ("So mau 16-bit", "Số mẫu 16-bit"),
        ("loai (viet 216 co the nham 2^16)", "loại (viết 216 có thể nhầm 2^16)"),
        ("ON NHANH TRUOC THI", "ÔN NHANH TRƯỚC THI"),
        ("Cach dung", "Cách dùng"),
        ("doc tung muc", "đọc từng mục"),
        ("tu viet lai so do", "tự viết lại sơ đồ"),
        ("lam bai Exercises cuoi chuong trong sach", "làm bài Exercises cuối chương trong sách"),
        ("File nay thay the ban", "File này thay thế bản"),
        ("chi tieu de", "chỉ tiêu đề"),
        ("moi dong la noi dung on that", "mỗi dòng là nội dung ôn thật"),
        ("Nguon:", "Nguồn:"),
        ("HET PHU LUC BO SUNG", "HẾT PHỤ LỤC BỔ SUNG"),
        ("PHU LUC BO SUNG", "PHỤ LỤC BỔ SUNG"),
        ("DOC THEM PHAN NAY KHI ON DE", "ĐỌC THÊM PHẦN NÀY KHI ÔN ĐỀ"),
        ("Bo sung sau khi doi chieu de mau", "Bổ sung sau khi đối chiếu đề mẫu"),
        ("CAC DIEM CAN DE TRA LOI CAU HOI MAU", "CÁC ĐIỂM CẦN ĐỂ TRẢ LỜI CÂU HỎI MẪU"),
    ]
    pairs.extend(extra)
    # unique keep first (longer preference via sort later)
    seen = set()
    out = []
    for a, b in pairs:
        if a not in seen:
            seen.add(a)
            out.append((a, b))
    out.sort(key=lambda x: -len(x[0]))
    return out


def main():
    path = ROOT / "TOM_TAT_ON_THI_FE_VOL1_VOL2.txt"
    text = path.read_text(encoding="utf-8")
    pairs = load_pairs()
    total = 0
    for a, b in pairs:
        if a in text:
            c = text.count(a)
            text = text.replace(a, b)
            total += c
    path.write_text(text, encoding="utf-8")
    print(f"Applied {total} replacements, {len(pairs)} pair rules")
    print(f"Diacritic chars: {sum(1 for ch in text if ord(ch) > 127)}")
    # rebuild study data
    subprocess.check_call([sys.executable, str(ROOT / "build_site_data.py")], cwd=str(ROOT))


if __name__ == "__main__":
    main()
